Flatpak build for [[https://apps.ankiweb.net/][Anki]], a powerful and intelligent flash card software.

To install: Configure the Flathub remote and run the system-wide or user install:
#+begin_src shell
# system install
flatpak install net.ankiweb.Anki

# user install
flatpak install --user net.ankiweb.Anki
#+end_src

Optional:
- mpv is already bundled together with the package for audio and video support
- Install =org.freedesktop.Sdk.Extension.texlive//25.08= if you want to use TeX

*** Known issues and troubleshooting
#+begin_html
<details>
<summary>X11: Fractional scaling does not work, only scales by whole numbers</summary>
Try running the app as follows: <code>flatpak run --env=QT_SCALE_FACTOR_ROUNDING_POLICY=passthrough net.ankiweb.Anki</code>. If scaling works properly, add an override with <code>flatpak override --env=QT_SCALE_FACTOR_ROUNDING_POLICY=passthrough net.ankiweb.Anki</code> or with Flatseal.
</details>
#+end_html

#+begin_html
<details>
<summary>X11: Menus in toolbar do not show up properly on theme change</summary>
Theme changes do not appear to hot-load properly on X11. Restart the application after changing the theme.
</details>
#+end_html

#+begin_html
<details>
<summary>MPV: How to disable (due to graphics problems, high cpu, or other reasons)</summary>
MPV is bundled with the app, but some people want to disable this due to issues with mpv (not the anki app). Here is how:

<ol>
<li>Find the addon directory (usually <code>~/.var/app/net.ankiweb.Anki/data/Anki2/addons</code>), <code>cd</code> to it.</li>
<li><code>mkdir nompv</code>, then <code>cd nompv</code></li>
<li>Add the contents of the following to  <code>__init.py__</code>: https://gist.github.com/rayes0/5fd3a629011846bd17d93fa9276080c7
</li>

This will stop mpv's idle process in anki and replace it with a dummy player. Audio and video will no longer work.

For more information, see https://github.com/flathub/net.ankiweb.Anki/issues/228
</ol>
   
</details>
#+end_html

#+html: <hr/>

Please report any issues in the issue tracker. Try to ensure your issues are specific to the flatpak, otherwise you will be redirected to the main Anki repo.
